export const facultyList = [
  {
    id: "CBIT2020",
    name: "Dr. Priya Sharma",
    department: "Computer Science & Engineering",
    designation: "Professor",
    mobile: "9876543210",
    qualification: "Ph.D",
    status: "pending",
    submitted: false,
    partA: { employeeId: "CBIT2020", name: "Dr. Priya Sharma", department: "Computer Science & Engineering", designation: "Professor", mobile: "9876543210", qualification: "Ph.D" },
    partB: {
      courses: {
        odd: [{ title: "Data Structures", code: "CS301", successRate: 92, gpa: 8.2, cosAttained: 4, proofPage: "12" }],
        even: [{ title: "Machine Learning", code: "CS501", successRate: 85, gpa: 8.0, cosAttained: 4, proofPage: "18" }],
      },
      feedback: [{ semester: "Odd 2024-25", course: "Data Structures", score: 4.2, proofPage: "22" }],
      pedagogy: [{ activity: "Flipped Classroom Model - CS301", proofPage: "30" }],
      mentoring: [{ role: "Class Advisor – 3rd Year CSE", students: 62, proofPage: "35" }],
    },
    partC: {
      conferencePapers: [{ title: "Deep Learning for Anomaly Detection in IoT", indexing: "Scopus", authorPos: "1st Author", points: 5, proofPage: "40" }],
      journalPapers: [{ title: "Transformer-based NLP for Code Summarization", quartile: "Q1", authorPos: "1st Author", points: 25, proofPage: "45" }],
      projects: [{ title: "AI-based Crop Yield Prediction – ICMR", agency: "ICMR", amount: "12,00,000", role: "PI", duration: "2023-25", proofPage: "50" }],
      patents: [{ title: "Smart Water Quality Monitoring System", type: "Published", number: "IN202341023456", proofPage: "55" }],
      consultancy: [],
    },
    partD: [{ activity: "Member – BOS, JNTUH (Computer Science)", level: "University", proofPage: "60" }],
    partE: { selfAppraisal: "During 2024-25, I focused on enhancing student engagement through technology-enabled teaching methods. I completed funded research and published Q1 journal papers." },
    scores: { partB: "", partC: "", partD: "", total: "" },
  },
  {
    id: "CBIT2026",
    name: "Dr. Ravi Kumar",
    department: "Computer Science & Engineering",
    designation: "Associate Professor",
    mobile: "9876543211",
    qualification: "Ph.D",
    status: "evaluated",
    submitted: true,
    partA: { employeeId: "CBIT2026", name: "Dr. Ravi Kumar", department: "Computer Science & Engineering", designation: "Associate Professor", mobile: "9876543211", qualification: "Ph.D" },
    partB: {
      courses: {
        odd: [{ title: "Database Management", code: "CS401", successRate: 90, gpa: 8.5, cosAttained: 4, proofPage: "12" }],
        even: [{ title: "Cloud Computing", code: "CS601", successRate: 83, gpa: 7.9, cosAttained: 3, proofPage: "13" }],
      },
      feedback: [{ semester: "Odd 2024-25", course: "DBMS", score: 4.1, proofPage: "20" }],
      pedagogy: [{ activity: "Case Study Based Teaching – Cloud Computing", proofPage: "25" }],
      mentoring: [{ role: "Class Advisor – 4th Year CSE", students: 58, proofPage: "28" }],
    },
    partC: {
      conferencePapers: [{ title: "Optimizing Query Execution in Distributed Databases", indexing: "Scopus", authorPos: "1st Author", points: 5, proofPage: "33" }],
      journalPapers: [{ title: "NoSQL Performance Benchmarking in Cloud", quartile: "Q2", authorPos: "1st Author", points: 15, proofPage: "36" }],
      projects: [],
      patents: [],
      consultancy: [{ title: "Database Optimization for ABC Pvt Ltd", amount: "1,50,000", proofPage: "40" }],
    },
    partD: [{ activity: "Coordinator – Technical Symposium 2024", level: "College", proofPage: "45" }],
    partE: { selfAppraisal: "In 2024-25, I contributed actively to teaching, research, and institutional development." },
    scores: { partB: "95", partC: "48", partD: "18", total: "161" },
  },
  {
    id: "CBIT2030",
    name: "Ms. Anitha Reddy",
    department: "Information Technology",
    designation: "Assistant Professor",
    mobile: "9876543212",
    qualification: "M.Tech",
    status: "pending",
    submitted: false,
    partA: { employeeId: "CBIT2030", name: "Ms. Anitha Reddy", department: "Information Technology", designation: "Assistant Professor", mobile: "9876543212", qualification: "M.Tech" },
    partB: {
      courses: {
        odd: [{ title: "Web Technologies", code: "IT301", successRate: 95, gpa: 8.8, cosAttained: 5, proofPage: "10" }],
        even: [{ title: "Software Engineering", code: "IT401", successRate: 91, gpa: 8.4, cosAttained: 4, proofPage: "12" }],
      },
      feedback: [{ semester: "Odd 2024-25", course: "Web Technologies", score: 4.7, proofPage: "18" }],
      pedagogy: [{ activity: "Hackathon for Web Development – 48 Hours", proofPage: "24" }],
      mentoring: [{ role: "Class Advisor – 2nd Year IT", students: 55, proofPage: "28" }],
    },
    partC: {
      conferencePapers: [{ title: "Progressive Web Applications: A Performance Study", indexing: "Scopus", authorPos: "1st Author", points: 5, proofPage: "32" }],
      journalPapers: [],
      projects: [],
      patents: [],
      consultancy: [],
    },
    partD: [{ activity: "Coordinator – Student Chapter (IEEE)", level: "College", proofPage: "38" }],
    partE: { selfAppraisal: "I have been consistently focused on delivering quality education and mentoring students in 2024-25." },
    scores: { partB: "", partC: "", partD: "", total: "" },
  },
  {
    id: "CBIT2035",
    name: "Dr. Suresh Babu",
    department: "Electronics & Communication Engineering",
    designation: "Professor",
    mobile: "9876543213",
    qualification: "Ph.D",
    status: "pending",
    submitted: false,
    partA: { employeeId: "CBIT2035", name: "Dr. Suresh Babu", department: "Electronics & Communication Engineering", designation: "Professor", mobile: "9876543213", qualification: "Ph.D" },
    partB: {
      courses: {
        odd: [{ title: "Signals & Systems", code: "EC301", successRate: 82, gpa: 7.5, cosAttained: 3, proofPage: "10" }],
        even: [{ title: "VLSI Design", code: "EC501", successRate: 78, gpa: 7.2, cosAttained: 3, proofPage: "11" }],
      },
      feedback: [{ semester: "Odd 2024-25", course: "Signals & Systems", score: 3.9, proofPage: "16" }],
      pedagogy: [{ activity: "MATLAB Simulation Lab – VLSI", proofPage: "21" }],
      mentoring: [{ role: "Ph.D. Supervisor – 4 scholars", students: 4, proofPage: "24" }],
    },
    partC: {
      conferencePapers: [{ title: "Low Power VLSI Circuit Design Using Adiabatic Logic", indexing: "IEEE Xplore", authorPos: "1st Author", points: 5, proofPage: "28" }],
      journalPapers: [{ title: "FPGA Implementation of Adaptive Filters", quartile: "Q1", authorPos: "1st Author", points: 25, proofPage: "33" }],
      projects: [{ title: "Smart Grid Monitoring – DST Funded", agency: "DST", amount: "8,50,000", role: "PI", duration: "2022-25", proofPage: "37" }],
      patents: [{ title: "Energy Harvesting Circuit for IoT Devices", type: "Granted", number: "IN202341067890", proofPage: "40" }],
      consultancy: [],
    },
    partD: [{ activity: "Best Paper Award – IETE National Conference 2024", level: "National", proofPage: "46" }],
    partE: { selfAppraisal: "I completed the DST-funded project on Smart Grid Monitoring. My patent on Energy Harvesting Circuit was granted this year." },
    scores: { partB: "", partC: "", partD: "", total: "" },
  },
  {
    id: "CBIT2040",
    name: "Dr. Kavitha Nair",
    department: "Artificial Intelligence & Data Science",
    designation: "Associate Professor",
    mobile: "9876543214",
    qualification: "Ph.D",
    status: "pending",
    submitted: false,
    partA: { employeeId: "CBIT2040", name: "Dr. Kavitha Nair", department: "Artificial Intelligence & Data Science", designation: "Associate Professor", mobile: "9876543214", qualification: "Ph.D" },
    partB: {
      courses: {
        odd: [{ title: "Deep Learning", code: "AI301", successRate: 88, gpa: 8.3, cosAttained: 4, proofPage: "10" }],
        even: [{ title: "Data Mining & Warehousing", code: "AI401", successRate: 86, gpa: 8.1, cosAttained: 4, proofPage: "11" }],
      },
      feedback: [{ semester: "Odd 2024-25", course: "Deep Learning", score: 4.4, proofPage: "16" }],
      pedagogy: [{ activity: "Kaggle Competition-based Learning", proofPage: "21" }],
      mentoring: [{ role: "Class Advisor – 3rd Year AI&DS", students: 60, proofPage: "24" }],
    },
    partC: {
      conferencePapers: [{ title: "Explainable AI for Medical Diagnosis", indexing: "Scopus", authorPos: "1st Author", points: 5, proofPage: "28" }],
      journalPapers: [{ title: "Predictive Analytics in Supply Chain Management", quartile: "Q2", authorPos: "1st Author", points: 15, proofPage: "32" }],
      projects: [{ title: "AI for Early Disease Detection – SERB Funded", agency: "SERB", amount: "10,00,000", role: "PI", duration: "2023-26", proofPage: "36" }],
      patents: [],
      consultancy: [],
    },
    partD: [{ activity: "Organizer – National Workshop on AI Ethics", level: "National", proofPage: "42" }],
    partE: { selfAppraisal: "I led a SERB-funded AI research project and mentored students through industry-relevant Kaggle competitions in 2024-25." },
    scores: { partB: "", partC: "", partD: "", total: "" },
  },
  {
    id: "CBIT2045",
    name: "Dr. Ramesh Yadav",
    department: "Mechanical Engineering",
    designation: "Professor",
    mobile: "9876543215",
    qualification: "Ph.D",
    status: "evaluated",
    submitted: true,
    partA: { employeeId: "CBIT2045", name: "Dr. Ramesh Yadav", department: "Mechanical Engineering", designation: "Professor", mobile: "9876543215", qualification: "Ph.D" },
    partB: {
      courses: {
        odd: [{ title: "Thermodynamics", code: "ME301", successRate: 80, gpa: 7.4, cosAttained: 3, proofPage: "10" }],
        even: [{ title: "Heat Transfer", code: "ME401", successRate: 78, gpa: 7.1, cosAttained: 3, proofPage: "11" }],
      },
      feedback: [{ semester: "Odd 2024-25", course: "Thermodynamics", score: 4.0, proofPage: "16" }],
      pedagogy: [{ activity: "Virtual Lab Simulations – Thermodynamics", proofPage: "21" }],
      mentoring: [{ role: "Class Advisor – 2nd Year Mech", students: 65, proofPage: "24" }],
    },
    partC: {
      conferencePapers: [{ title: "Thermal Analysis of Composite Materials", indexing: "Scopus", authorPos: "1st Author", points: 5, proofPage: "28" }],
      journalPapers: [{ title: "CFD Simulation of Turbulent Flows in Heat Exchangers", quartile: "Q1", authorPos: "1st Author", points: 25, proofPage: "32" }],
      projects: [],
      patents: [{ title: "Energy Efficient Heat Exchanger Design", type: "Granted", number: "IN202341078901", proofPage: "38" }],
      consultancy: [{ title: "Thermal Design Review – XYZ Industries", amount: "2,00,000", proofPage: "42" }],
    },
    partD: [{ activity: "Member – Board of Studies, JNTUH Mechanical", level: "University", proofPage: "46" }],
    partE: { selfAppraisal: "I actively contributed to thermal engineering research and guided students through project-based learning using virtual labs." },
    scores: { partB: "88", partC: "52", partD: "20", total: "160" },
  },
  {
    id: "CBIT2050",
    name: "Ms. Deepika Patel",
    department: "Civil Engineering",
    designation: "Assistant Professor",
    mobile: "9876543216",
    qualification: "M.Tech",
    status: "pending",
    submitted: false,
    partA: { employeeId: "CBIT2050", name: "Ms. Deepika Patel", department: "Civil Engineering", designation: "Assistant Professor", mobile: "9876543216", qualification: "M.Tech" },
    partB: {
      courses: {
        odd: [{ title: "Structural Analysis", code: "CE301", successRate: 87, gpa: 7.8, cosAttained: 4, proofPage: "10" }],
        even: [{ title: "Geotechnical Engineering", code: "CE401", successRate: 84, gpa: 7.6, cosAttained: 3, proofPage: "11" }],
      },
      feedback: [{ semester: "Odd 2024-25", course: "Structural Analysis", score: 4.2, proofPage: "16" }],
      pedagogy: [{ activity: "AutoCAD & STAAD Pro Workshop for Students", proofPage: "21" }],
      mentoring: [{ role: "Class Advisor – 1st Year Civil", students: 70, proofPage: "24" }],
    },
    partC: {
      conferencePapers: [{ title: "Seismic Analysis of Multi-Storey Buildings", indexing: "Scopus", authorPos: "1st Author", points: 5, proofPage: "28" }],
      journalPapers: [],
      projects: [],
      patents: [],
      consultancy: [],
    },
    partD: [{ activity: "Coordinator – Civil Engineering Society, CBIT", level: "College", proofPage: "34" }],
    partE: { selfAppraisal: "I conducted workshops on structural design tools and helped students gain practical exposure to industry-standard software during 2024-25." },
    scores: { partB: "", partC: "", partD: "", total: "" },
  },
  {
    id: "CBIT2055",
    name: "Dr. Anil Verma",
    department: "Electrical & Electronics Engineering",
    designation: "Associate Professor",
    mobile: "9876543217",
    qualification: "Ph.D",
    status: "pending",
    submitted: false,
    partA: { employeeId: "CBIT2055", name: "Dr. Anil Verma", department: "Electrical & Electronics Engineering", designation: "Associate Professor", mobile: "9876543217", qualification: "Ph.D" },
    partB: {
      courses: {
        odd: [{ title: "Power Systems", code: "EE301", successRate: 83, gpa: 7.6, cosAttained: 3, proofPage: "10" }],
        even: [{ title: "Control Systems", code: "EE401", successRate: 81, gpa: 7.4, cosAttained: 3, proofPage: "11" }],
      },
      feedback: [{ semester: "Odd 2024-25", course: "Power Systems", score: 4.1, proofPage: "16" }],
      pedagogy: [{ activity: "MATLAB-based Control Systems Lab", proofPage: "21" }],
      mentoring: [{ role: "Class Advisor – 3rd Year EEE", students: 58, proofPage: "24" }],
    },
    partC: {
      conferencePapers: [{ title: "Smart Grid Load Forecasting Using ML", indexing: "IEEE Xplore", authorPos: "1st Author", points: 5, proofPage: "28" }],
      journalPapers: [{ title: "Renewable Energy Integration in Power Grids", quartile: "Q2", authorPos: "Co-Author", points: 15, proofPage: "32" }],
      projects: [{ title: "Solar Power Optimization – MNRE Funded", agency: "MNRE", amount: "6,00,000", role: "Co-PI", duration: "2023-25", proofPage: "36" }],
      patents: [],
      consultancy: [],
    },
    partD: [{ activity: "Resource Person – State Level Workshop on Smart Grids", level: "State", proofPage: "42" }],
    partE: { selfAppraisal: "My focus in 2024-25 has been on smart grid research and renewable energy systems. I co-investigated an MNRE-funded project." },
    scores: { partB: "", partC: "", partD: "", total: "" },
  },
  {
    id: "CBIT2060",
    name: "Dr. Shalini Gupta",
    department: "Chemical Engineering",
    designation: "Professor",
    mobile: "9876543218",
    qualification: "Ph.D",
    status: "pending",
    submitted: false,
    partA: { employeeId: "CBIT2060", name: "Dr. Shalini Gupta", department: "Chemical Engineering", designation: "Professor", mobile: "9876543218", qualification: "Ph.D" },
    partB: {
      courses: {
        odd: [{ title: "Chemical Reaction Engineering", code: "CH301", successRate: 85, gpa: 7.9, cosAttained: 4, proofPage: "10" }],
        even: [{ title: "Mass Transfer Operations", code: "CH401", successRate: 82, gpa: 7.6, cosAttained: 3, proofPage: "11" }],
      },
      feedback: [{ semester: "Odd 2024-25", course: "Chemical Reaction Engineering", score: 4.3, proofPage: "16" }],
      pedagogy: [{ activity: "Aspen Plus Simulation Sessions", proofPage: "21" }],
      mentoring: [{ role: "Ph.D. Supervisor – 3 scholars", students: 3, proofPage: "24" }],
    },
    partC: {
      conferencePapers: [{ title: "Catalytic Conversion of Biomass to Biofuels", indexing: "Scopus", authorPos: "1st Author", points: 5, proofPage: "28" }],
      journalPapers: [{ title: "Green Chemistry Approaches in Industrial Processes", quartile: "Q1", authorPos: "1st Author", points: 25, proofPage: "32" }],
      projects: [{ title: "Green Hydrogen Production – DBT Funded", agency: "DBT", amount: "15,00,000", role: "PI", duration: "2022-25", proofPage: "36" }],
      patents: [{ title: "Bioreactor Design for Enhanced Enzyme Production", type: "Granted", number: "IN202341089012", proofPage: "40" }],
      consultancy: [],
    },
    partD: [{ activity: "Expert Member – AICTE Inspection Committee", level: "National", proofPage: "46" }],
    partE: { selfAppraisal: "I led a DBT-funded project on Green Hydrogen Production and published in Q1 journals. I guided Ph.D. scholars and participated in national committees." },
    scores: { partB: "", partC: "", partD: "", total: "" },
  },
  {
    id: "CBIT2065",
    name: "Mr. Kiran Teja",
    department: "Computer Science & Engineering (IoT)",
    designation: "Assistant Professor",
    mobile: "9876543219",
    qualification: "M.Tech",
    status: "pending",
    submitted: false,
    partA: { employeeId: "CBIT2065", name: "Mr. Kiran Teja", department: "Computer Science & Engineering (IoT)", designation: "Assistant Professor", mobile: "9876543219", qualification: "M.Tech" },
    partB: {
      courses: {
        odd: [{ title: "Internet of Things", code: "IoT301", successRate: 91, gpa: 8.4, cosAttained: 4, proofPage: "10" }],
        even: [{ title: "Embedded Systems", code: "IoT401", successRate: 88, gpa: 8.0, cosAttained: 4, proofPage: "11" }],
      },
      feedback: [{ semester: "Odd 2024-25", course: "IoT", score: 4.5, proofPage: "16" }],
      pedagogy: [{ activity: "Arduino & Raspberry Pi Hands-on Workshop", proofPage: "21" }],
      mentoring: [{ role: "Class Advisor – 2nd Year IoT", students: 52, proofPage: "24" }],
    },
    partC: {
      conferencePapers: [{ title: "Smart Home Automation Using IoT and AI", indexing: "Scopus", authorPos: "1st Author", points: 5, proofPage: "28" }],
      journalPapers: [],
      projects: [],
      patents: [],
      consultancy: [],
    },
    partD: [{ activity: "Organized Hackathon – IoT Innovation Challenge 2024", level: "College", proofPage: "34" }],
    partE: { selfAppraisal: "I focused on hands-on IoT education and conducted practical workshops using hardware kits for students in 2024-25." },
    scores: { partB: "", partC: "", partD: "", total: "" },
  },
  {
    id: "CBIT2070",
    name: "Dr. Madhuri Rao",
    department: "Computer Science & Engineering (Cyber Security)",
    designation: "Associate Professor",
    mobile: "9876543220",
    qualification: "Ph.D",
    status: "pending",
    submitted: false,
    partA: { employeeId: "CBIT2070", name: "Dr. Madhuri Rao", department: "Computer Science & Engineering (Cyber Security)", designation: "Associate Professor", mobile: "9876543220", qualification: "Ph.D" },
    partB: {
      courses: {
        odd: [{ title: "Network Security", code: "CS401", successRate: 89, gpa: 8.2, cosAttained: 4, proofPage: "10" }],
        even: [{ title: "Cryptography & Information Security", code: "CS501", successRate: 87, gpa: 8.0, cosAttained: 4, proofPage: "11" }],
      },
      feedback: [{ semester: "Odd 2024-25", course: "Network Security", score: 4.4, proofPage: "16" }],
      pedagogy: [{ activity: "CTF (Capture The Flag) Competitions for Students", proofPage: "21" }],
      mentoring: [{ role: "Class Advisor – 3rd Year Cyber Security", students: 55, proofPage: "24" }],
    },
    partC: {
      conferencePapers: [{ title: "Zero Trust Architecture in Cloud Security", indexing: "Scopus", authorPos: "1st Author", points: 5, proofPage: "28" }],
      journalPapers: [{ title: "Blockchain-based Data Integrity Verification", quartile: "Q2", authorPos: "1st Author", points: 15, proofPage: "32" }],
      projects: [],
      patents: [],
      consultancy: [{ title: "Cyber Security Audit – PQR Bank", amount: "3,50,000", proofPage: "38" }],
    },
    partD: [{ activity: "Resource Person – National Cyber Security Awareness Week", level: "National", proofPage: "44" }],
    partE: { selfAppraisal: "I organized CTF competitions and conducted a cyber security consultancy for a banking client in 2024-25." },
    scores: { partB: "", partC: "", partD: "", total: "" },
  },
  {
    id: "CBIT2075",
    name: "Dr. Venkat Reddy",
    department: "Bio Technology",
    designation: "Professor",
    mobile: "9876543221",
    qualification: "Ph.D",
    status: "evaluated",
    submitted: true,
    partA: { employeeId: "CBIT2075", name: "Dr. Venkat Reddy", department: "Bio Technology", designation: "Professor", mobile: "9876543221", qualification: "Ph.D" },
    partB: {
      courses: {
        odd: [{ title: "Molecular Biology", code: "BT301", successRate: 86, gpa: 7.9, cosAttained: 4, proofPage: "10" }],
        even: [{ title: "Genetic Engineering", code: "BT401", successRate: 83, gpa: 7.7, cosAttained: 3, proofPage: "11" }],
      },
      feedback: [{ semester: "Odd 2024-25", course: "Molecular Biology", score: 4.2, proofPage: "16" }],
      pedagogy: [{ activity: "Lab-based Problem Solving in Biotechnology", proofPage: "21" }],
      mentoring: [{ role: "Ph.D. Supervisor – 2 scholars", students: 2, proofPage: "24" }],
    },
    partC: {
      conferencePapers: [{ title: "CRISPR-Cas9 Applications in Gene Therapy", indexing: "Scopus", authorPos: "1st Author", points: 5, proofPage: "28" }],
      journalPapers: [{ title: "Microbial Production of Industrial Enzymes", quartile: "Q1", authorPos: "1st Author", points: 25, proofPage: "32" }],
      projects: [{ title: "Bioremediation of Industrial Waste – DBT Funded", agency: "DBT", amount: "9,00,000", role: "PI", duration: "2022-25", proofPage: "36" }],
      patents: [],
      consultancy: [],
    },
    partD: [{ activity: "Member – Editorial Board, Journal of Biotechnology", level: "International", proofPage: "42" }],
    partE: { selfAppraisal: "I completed a DBT-funded project and published high-impact research in Q1 journals. I supervised Ph.D. scholars and contributed to editorial boards." },
    scores: { partB: "90", partC: "55", partD: "22", total: "167" },
  },
  {
    id: "CBIT2080",
    name: "Dr. Prakash Mehta",
    department: "Mining Engineering",
    designation: "Associate Professor",
    mobile: "9876543222",
    qualification: "Ph.D",
    status: "pending",
    submitted: false,
    partA: { employeeId: "CBIT2080", name: "Dr. Prakash Mehta", department: "Mining Engineering", designation: "Associate Professor", mobile: "9876543222", qualification: "Ph.D" },
    partB: {
      courses: {
        odd: [{ title: "Rock Mechanics", code: "MN301", successRate: 80, gpa: 7.3, cosAttained: 3, proofPage: "10" }],
        even: [{ title: "Mine Ventilation", code: "MN401", successRate: 78, gpa: 7.1, cosAttained: 3, proofPage: "11" }],
      },
      feedback: [{ semester: "Odd 2024-25", course: "Rock Mechanics", score: 3.8, proofPage: "16" }],
      pedagogy: [{ activity: "Field Visit to Singareni Mines for Students", proofPage: "21" }],
      mentoring: [{ role: "Class Advisor – 2nd Year Mining", students: 45, proofPage: "24" }],
    },
    partC: {
      conferencePapers: [{ title: "Slope Stability Analysis Using Numerical Methods", indexing: "Scopus", authorPos: "1st Author", points: 5, proofPage: "28" }],
      journalPapers: [],
      projects: [],
      patents: [],
      consultancy: [{ title: "Geological Survey Consultancy – SCCL", amount: "4,00,000", proofPage: "34" }],
    },
    partD: [{ activity: "Expert Lecture – Institute of Mining Engineers of India", level: "National", proofPage: "40" }],
    partE: { selfAppraisal: "I provided consultancy to SCCL and organized field visits for students to gain practical exposure to mining operations in 2024-25." },
    scores: { partB: "", partC: "", partD: "", total: "" },
  },
  {
    id: "CBIT2085",
    name: "Dr. Lakshmi Prasad",
    department: "Electronics & Computer Engineering",
    designation: "Assistant Professor",
    mobile: "9876543223",
    qualification: "Ph.D",
    status: "pending",
    submitted: false,
    partA: { employeeId: "CBIT2085", name: "Dr. Lakshmi Prasad", department: "Electronics & Computer Engineering", designation: "Assistant Professor", mobile: "9876543223", qualification: "Ph.D" },
    partB: {
      courses: {
        odd: [{ title: "Digital Signal Processing", code: "EC401", successRate: 84, gpa: 7.8, cosAttained: 4, proofPage: "10" }],
        even: [{ title: "Microprocessors & Microcontrollers", code: "EC501", successRate: 82, gpa: 7.6, cosAttained: 3, proofPage: "11" }],
      },
      feedback: [{ semester: "Odd 2024-25", course: "DSP", score: 4.1, proofPage: "16" }],
      pedagogy: [{ activity: "TinkerCAD Simulation-based Learning", proofPage: "21" }],
      mentoring: [{ role: "Class Advisor – 2nd Year ECE", students: 60, proofPage: "24" }],
    },
    partC: {
      conferencePapers: [{ title: "Real-time Speech Recognition Using DSP Processors", indexing: "IEEE Xplore", authorPos: "1st Author", points: 5, proofPage: "28" }],
      journalPapers: [{ title: "Noise Cancellation Algorithms for Embedded Systems", quartile: "Q2", authorPos: "Co-Author", points: 15, proofPage: "32" }],
      projects: [],
      patents: [],
      consultancy: [],
    },
    partD: [{ activity: "Coordinator – Technical Fest, CBIT 2024", level: "College", proofPage: "38" }],
    partE: { selfAppraisal: "I focused on simulation-based teaching and published in IEEE journals. I also coordinated the annual technical fest in 2024-25." },
    scores: { partB: "", partC: "", partD: "", total: "" },
  },
];